### ISSUE TITLE
Testing Issue #296 (in-thread)

### ISSUE THREAD

**Issue by magneticstain** [magneticstain/ip-2-cloudresource#298]
View details in Rollbar: [https://app.rollbar.com/a/magneticstain/fix/item/IP-2-CloudResource/10](https://app.rollbar.com/a/magneticstain/fix/item/IP-2-CloudResource/10)

```
Traceback (most recent call last):
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 422, in rollbar-go.(*Client).ErrorWithStackSkipWithExtras
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 415, in rollbar-go.(*Client).ErrorWithStackSkip
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 537, in rollbar-go.(*Client).LogPanic
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 576, in rollbar-go.(*Client).WrapWithArgs.func1.1
  File "/usr/local/go/src/runtime/panic.go", line 920, in runtime.gopanic
  File "/home/josh/Code/ip-2-cloudresource/src/search/search.go", line 161, in search.Search.runSearchWorker
  File "/usr/local/go/src/reflect/value.go", line 596, in reflect.Value.call
  File "/usr/local/go/src/reflect/value.go", line 380, in reflect.Value.Call
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 579, in rollbar-go.(*Client).WrapWithArgs.func1
  File "github.com/rollbar/rollbar-go@v1.4.5/client.go", line 582, in rollbar-go.(*Client).WrapWithArgs
  File "github.com/rollbar/rollbar-go@v1.4.5/rollbar.go", line 649, in rollbar-go.WrapAndWait
  File "/usr/local/go/src/runtime/asm_amd64.s", line 1650, in runtime.goexit
errors.errorString: Testing Issue #296 (in-thread)
```

**Comment by magneticstain** [comment]
Related to #296
